language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install -r tests/requirements.txt
  - pip install -r styling_requirements.txt
  - if [ $TRAVIS_BRANCH == "stable" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
      export POUTYNE_RELEASE_BUILD=1;
    else
      export POUTYNE_RELEASE_BUILD=0;
    fi
  - python setup.py develop
script:
  - yapf --diff --recursive poutyne/
  - yapf --diff --recursive tests/
  - pylint poutyne/
  - pylint tests/
  - pytest tests/
  - cd docs
  - ./rebuild_html_doc.sh
  - cd ..
deploy:
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local-dir: "./docs/_build/html/"
  provider: pages
  on:
    branch: stable
