name: Continuous Integration

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - name: Set deploy environment variable
      run: |
        # POUTYNE_RELEASE_BUILD is also used in setup.py
        if [ $GITHUB_REF == "refs/heads/stable" ] && \
           [ $GITHUB_EVENT_NAME == "push" ] && \
           [ ${{ matrix.python-version }} == "3.9" ]; then
          echo "POUTYNE_RELEASE_BUILD=1" >> $GITHUB_ENV
        else
          echo "POUTYNE_RELEASE_BUILD=0" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        pip install -r tests/requirements.txt
        pip install -r styling_requirements.txt
        python setup.py develop
    - name: Linting
      run: |
        black --diff --check .
        pylint poutyne/
        pylint tests/
    - name: Test with pytest
      run: |
        pytest
    - name: Upload Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
    - name: Building doc
      run: |
        cd docs
        ./rebuild_html_doc.sh
        cd ..
    - name: Deploy
      if: env.POUTYNE_RELEASE_BUILD == '1'
      uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/

  windowsbuild:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        .  ./InvokeFunc.ps1
        Invoke-NativeCommand pip install -r requirements.txt
        Invoke-NativeCommand pip install -r docs/requirements.txt
        Invoke-NativeCommand pip install -r tests/requirements.txt
        Invoke-NativeCommand pip install -r styling_requirements.txt
        Invoke-NativeCommand python setup.py develop
    - name: Linting
      run: |
        .  ./InvokeFunc.ps1
        Invoke-NativeCommand black --diff --check .
        Invoke-NativeCommand pylint poutyne/
        Invoke-NativeCommand pylint tests/
    - name: Test with pytest
      run: |
        .  ./InvokeFunc.ps1
        Invoke-NativeCommand pytest
    - name: Upload Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
    - name: Building doc
      run: |
        cd docs
        ./rebuild_html_doc.ps1
        cd ..
